description = "add translation"
prompt= """
{{args}} translate missing content using technical terms from source language column en (English) and target language according to iso code in the header. Add content in TSV format. 
""" 